project:
  # namespace
  k8s_namespace: data-mill
  # the port on which the K8s UI is exposed
  proxy_port: 8088
  # the flavour is used to list all the components to be used in the project
  flavour: all
  # k8s default config, can be overwritten with -t filename
  k8s_default_config: default_uc.yaml
  # k8s_default_config is not necessary in this example, since we provide the target cluster
  # already in this file
  # component default config, can be overwritten with -f filename
  component_default_config: config.yaml
  # set the data folder
  data_folder: data

ambassador:
  release: ambassador
  config_file: ambassador_config.yaml
  diagnostic_ui: true

local:
  cpus: 8
  memory: 16288
  storage: 60G
  gpu_support: true
  use_overlay: false
  provider: microk8s
  use_multipass: false
  istio_support: true

remote:
  provider: aws
  cluster_name: data-mill
  bucket_name: data-mill
  region: "us-east1"
  zones: "us-east1a"
  no_nodes: 2
  node_size: t2.medium

hybrid:
  # use the local microk8s config to test it
  config: "~/Documents/data-mill/infrastructure/k8s/microk8s.config"
